/**
 * vocabulary.js — Vocabulario completo del juego BeiMax
 * Mínimo 80 palabras por categoría, 3 idiomas (es, en, fr)
 * con pronunciación aproximada y sinónimos para validación flexible
 */

// ========== DATOS DE CATEGORÍAS ==========
const categoryData = {
    kitchen: {
        name: { es: 'Cocina', en: 'Kitchen', fr: 'Cuisine' },
        items: [
            // --- Utensilios básicos ---
            {emoji:'🔪', es:'cuchillo', en:'knife', fr:'couteau', pron_es:'ku-CHI-yo', pron_en:'naif', pron_fr:'ku-TÓ'},
            {emoji:'🍴', es:'tenedor', en:'fork', fr:'fourchette', pron_es:'te-ne-DOR', pron_en:'fork', pron_fr:'fur-SHET'},
            {emoji:'🥄', es:'cuchara', en:'spoon', fr:'cuillère', pron_es:'ku-CHA-ra', pron_en:'spuun', pron_fr:'kui-ÉR'},
            {emoji:'🍳', es:'sartén', en:'pan', fr:'poêle', pron_es:'sar-TÉN', pron_en:'pan', pron_fr:'pual'},
            {emoji:'🫖', es:'tetera', en:'teapot', fr:'théière', pron_es:'te-TE-ra', pron_en:'tíi-pot', pron_fr:'te-IÉR'},
            {emoji:'🍽️', es:'plato', en:'plate', fr:'assiette', pron_es:'PLA-to', pron_en:'pleit', pron_fr:'a-SIÉT'},
            {emoji:'🥛', es:'vaso', en:'glass', fr:'verre', pron_es:'BA-so', pron_en:'glas', pron_fr:'ver'},
            {emoji:'🧊', es:'hielo', en:'ice', fr:'glace', pron_es:'IE-lo', pron_en:'ais', pron_fr:'glas'},
            // --- Electrodomésticos ---
            {emoji:'🍞', es:'tostadora', en:'toaster', fr:'grille-pain', pron_es:'tos-ta-DO-ra', pron_en:'TOUS-ter', pron_fr:'gri-PÉN'},
            {emoji:'🫙', es:'licuadora', en:'blender', fr:'mixeur', pron_es:'li-kua-DO-ra', pron_en:'BLEN-der', pron_fr:'mik-SÉR'},
            {emoji:'🔥', es:'horno', en:'oven', fr:'four', pron_es:'OR-no', pron_en:'A-ven', pron_fr:'fur'},
            {emoji:'❄️', es:'refrigerador', en:'refrigerator', fr:'réfrigérateur', pron_es:'re-fri-je-ra-DOR', pron_en:'ri-FRI-ye-rei-tor', pron_fr:'re-fri-je-ra-TÉR'},
            {emoji:'💨', es:'microondas', en:'microwave', fr:'micro-ondes', pron_es:'mi-kro-ON-das', pron_en:'MAI-kro-ueiv', pron_fr:'mi-kro-ÓND'},
            {emoji:'🫗', es:'cafetera', en:'coffee maker', fr:'cafetière', pron_es:'ka-fe-TE-ra', pron_en:'KO-fi MEI-ker', pron_fr:'ka-fe-TIÉR'},
            {emoji:'🧹', es:'lavavajillas', en:'dishwasher', fr:'lave-vaisselle', pron_es:'la-va-ba-JI-yas', pron_en:'DISH-UO-sher', pron_fr:'lav-ve-SÉL'},
            {emoji:'🍕', es:'horno de pizza', en:'pizza oven', fr:'four à pizza', pron_es:'OR-no de PI-sa', pron_en:'PII-tsa A-ven', pron_fr:'fur a PI-tsa'},
            // --- Recipientes y contenedores ---
            {emoji:'🥣', es:'tazón', en:'bowl', fr:'bol', pron_es:'ta-SÓN', pron_en:'boul', pron_fr:'bol'},
            {emoji:'☕', es:'taza', en:'cup', fr:'tasse', pron_es:'TA-sa', pron_en:'kap', pron_fr:'tas'},
            {emoji:'🍶', es:'jarra', en:'pitcher', fr:'carafe', pron_es:'JA-rra', pron_en:'PI-cher', pron_fr:'ka-RAF'},
            {emoji:'🧴', es:'botella', en:'bottle', fr:'bouteille', pron_es:'bo-TE-ya', pron_en:'BO-tel', pron_fr:'bu-TEY'},
            {emoji:'🫕', es:'olla', en:'pot', fr:'marmite', pron_es:'O-ya', pron_en:'pot', pron_fr:'mar-MIT'},
            {emoji:'🥘', es:'cacerola', en:'saucepan', fr:'casserole', pron_es:'ka-se-RO-la', pron_en:'SOS-pan', pron_fr:'ka-se-ROL'},
            {emoji:'🧃', es:'bandeja', en:'tray', fr:'plateau', pron_es:'ban-DE-ja', pron_en:'trei', pron_fr:'pla-TÓ'},
            {emoji:'🫙', es:'frasco', en:'jar', fr:'bocal', pron_es:'FRAS-ko', pron_en:'yar', pron_fr:'bo-KAL'},
            // --- Herramientas de cocina ---
            {emoji:'🥢', es:'palillos', en:'chopsticks', fr:'baguettes', pron_es:'pa-LI-yos', pron_en:'CHOP-stiks', pron_fr:'ba-GUET'},
            {emoji:'🔪', es:'tabla de cortar', en:'cutting board', fr:'planche à découper', pron_es:'TA-bla de kor-TAR', pron_en:'KA-ting bord', pron_fr:'plansh a de-ku-PÉ'},
            {emoji:'🧄', es:'rallador', en:'grater', fr:'râpe', pron_es:'ra-ya-DOR', pron_en:'GREI-ter', pron_fr:'rap'},
            {emoji:'⏱️', es:'temporizador', en:'timer', fr:'minuteur', pron_es:'tem-po-ri-sa-DOR', pron_en:'TAI-mer', pron_fr:'mi-nu-TÉR'},
            {emoji:'🧽', es:'esponja', en:'sponge', fr:'éponge', pron_es:'es-PON-ja', pron_en:'sponch', pron_fr:'e-PONJ'},
            {emoji:'🧻', es:'servilleta', en:'napkin', fr:'serviette', pron_es:'ser-bi-YE-ta', pron_en:'NAP-kin', pron_fr:'ser-VIÉT'},
            {emoji:'🧈', es:'mantequilla', en:'butter', fr:'beurre', pron_es:'man-te-KI-ya', pron_en:'BA-ter', pron_fr:'ber'},
            {emoji:'🧂', es:'sal', en:'salt', fr:'sel', pron_es:'sal', pron_en:'solt', pron_fr:'sel'},
            {emoji:'🌶️', es:'pimienta', en:'pepper', fr:'poivre', pron_es:'pi-MIÉN-ta', pron_en:'PE-per', pron_fr:'PUAVR'},
            {emoji:'🫒', es:'aceite', en:'oil', fr:'huile', pron_es:'a-SEI-te', pron_en:'oil', pron_fr:'uil'},
            {emoji:'🍯', es:'miel', en:'honey', fr:'miel', pron_es:'miel', pron_en:'JA-ni', pron_fr:'miel'},
            {emoji:'🥚', es:'huevo', en:'egg', fr:'œuf', pron_es:'UE-bo', pron_en:'eg', pron_fr:'ef'},
            {emoji:'🍚', es:'arroz', en:'rice', fr:'riz', pron_es:'a-RRÓS', pron_en:'rais', pron_fr:'rí'},
            {emoji:'🍞', es:'pan', en:'bread', fr:'pain', pron_es:'pan', pron_en:'bred', pron_fr:'pen'},
            {emoji:'🥩', es:'carne', en:'meat', fr:'viande', pron_es:'KAR-ne', pron_en:'miit', pron_fr:'viánd'},
            {emoji:'🐟', es:'pescado', en:'fish', fr:'poisson', pron_es:'pes-KA-do', pron_en:'fish', pron_fr:'pua-SÓN'},
            {emoji:'🧀', es:'queso', en:'cheese', fr:'fromage', pron_es:'KE-so', pron_en:'chiis', pron_fr:'fro-MASH'},
            {emoji:'🥕', es:'zanahoria', en:'carrot', fr:'carotte', pron_es:'sa-na-O-ria', pron_en:'KA-rot', pron_fr:'ka-ROT'},
            {emoji:'🍅', es:'tomate', en:'tomato', fr:'tomate', pron_es:'to-MA-te', pron_en:'to-MEI-to', pron_fr:'to-MAT'},
            {emoji:'🧅', es:'cebolla', en:'onion', fr:'oignon', pron_es:'se-BO-ya', pron_en:'A-nion', pron_fr:'o-ÑÓN'},
            {emoji:'🥔', es:'papa', en:'potato', fr:'pomme de terre', pron_es:'PA-pa', pron_en:'po-TEI-to', pron_fr:'pom de TER'},
            {emoji:'🥬', es:'lechuga', en:'lettuce', fr:'laitue', pron_es:'le-CHU-ga', pron_en:'LE-tis', pron_fr:'le-TÜ'},
            {emoji:'🍋', es:'limón', en:'lemon', fr:'citron', pron_es:'li-MÓN', pron_en:'LE-mon', pron_fr:'si-TRÓN'},
            {emoji:'🍎', es:'manzana', en:'apple', fr:'pomme', pron_es:'man-SA-na', pron_en:'A-pel', pron_fr:'pom'},
            {emoji:'🍌', es:'plátano', en:'banana', fr:'banane', pron_es:'PLÁ-ta-no', pron_en:'ba-NA-na', pron_fr:'ba-NAN'},
            {emoji:'🍊', es:'naranja', en:'orange', fr:'orange', pron_es:'na-RAN-ja', pron_en:'O-rinch', pron_fr:'o-RANJ'},
            {emoji:'🍇', es:'uva', en:'grape', fr:'raisin', pron_es:'U-ba', pron_en:'greip', pron_fr:'re-ZÉN'},
            {emoji:'🍓', es:'fresa', en:'strawberry', fr:'fraise', pron_es:'FRE-sa', pron_en:'STRO-be-ri', pron_fr:'frez'},
            {emoji:'🍉', es:'sandía', en:'watermelon', fr:'pastèque', pron_es:'san-DÍ-a', pron_en:'UÓ-ter-me-lon', pron_fr:'pas-TEK'},
            {emoji:'🥑', es:'aguacate', en:'avocado', fr:'avocat', pron_es:'a-gua-KA-te', pron_en:'a-vo-KA-do', pron_fr:'a-vo-KÁ'},
            {emoji:'🍍', es:'piña', en:'pineapple', fr:'ananas', pron_es:'PI-ña', pron_en:'PAIN-a-pel', pron_fr:'a-na-NÁS'},
            {emoji:'🥥', es:'coco', en:'coconut', fr:'noix de coco', pron_es:'KO-ko', pron_en:'KOU-ko-nat', pron_fr:'nua de KO-ko'},
            {emoji:'🥒', es:'pepino', en:'cucumber', fr:'concombre', pron_es:'pe-PI-no', pron_en:'KIUU-kam-ber', pron_fr:'kon-KOMBR'},
            {emoji:'🫑', es:'pimiento', en:'bell pepper', fr:'poivron', pron_es:'pi-MIÉN-to', pron_en:'bel PE-per', pron_fr:'pua-VRÓN'},
            {emoji:'🍄', es:'champiñón', en:'mushroom', fr:'champignon', pron_es:'cham-pi-ÑÓN', pron_en:'MASH-rum', pron_fr:'sham-pi-ÑÓN'},
            {emoji:'🌽', es:'maíz', en:'corn', fr:'maïs', pron_es:'ma-ÍS', pron_en:'korn', pron_fr:'ma-ÍS'},
            {emoji:'🥦', es:'brócoli', en:'broccoli', fr:'brocoli', pron_es:'BRÓ-ko-li', pron_en:'BRÓ-ko-li', pron_fr:'bro-ko-LÍ'},
            {emoji:'🍝', es:'pasta', en:'pasta', fr:'pâtes', pron_es:'PAS-ta', pron_en:'PAS-ta', pron_fr:'pat'},
            {emoji:'🥜', es:'cacahuate', en:'peanut', fr:'cacahuète', pron_es:'ka-ka-UA-te', pron_en:'PII-nat', pron_fr:'ka-ka-UÉT'},
            {emoji:'🍫', es:'chocolate', en:'chocolate', fr:'chocolat', pron_es:'cho-ko-LA-te', pron_en:'CHO-ko-lat', pron_fr:'sho-ko-LÁ'},
            {emoji:'🍦', es:'helado', en:'ice cream', fr:'glace', pron_es:'e-LA-do', pron_en:'ais kriim', pron_fr:'glas'},
            {emoji:'🎂', es:'pastel', en:'cake', fr:'gâteau', pron_es:'pas-TEL', pron_en:'keik', pron_fr:'ga-TÓ'},
            {emoji:'🍪', es:'galleta', en:'cookie', fr:'biscuit', pron_es:'ga-YE-ta', pron_en:'KU-ki', pron_fr:'bis-KUÍ'},
            {emoji:'🥛', es:'leche', en:'milk', fr:'lait', pron_es:'LE-che', pron_en:'milk', pron_fr:'le'},
            {emoji:'☕', es:'café', en:'coffee', fr:'café', pron_es:'ka-FÉ', pron_en:'KO-fi', pron_fr:'ka-FÉ'},
            {emoji:'🧃', es:'jugo', en:'juice', fr:'jus', pron_es:'JU-go', pron_en:'yus', pron_fr:'jü'},
            {emoji:'💧', es:'agua', en:'water', fr:'eau', pron_es:'A-gua', pron_en:'UÓ-ter', pron_fr:'ó'},
            {emoji:'🍵', es:'té', en:'tea', fr:'thé', pron_es:'te', pron_en:'tii', pron_fr:'te'},
            {emoji:'🧁', es:'magdalena', en:'muffin', fr:'muffin', pron_es:'mag-da-LE-na', pron_en:'MA-fin', pron_fr:'MA-fin'},
            {emoji:'🥐', es:'croissant', en:'croissant', fr:'croissant', pron_es:'krua-SÁN', pron_en:'krua-SANT', pron_fr:'krua-SÁN'},
            {emoji:'🥖', es:'baguette', en:'baguette', fr:'baguette', pron_es:'ba-GUET', pron_en:'ba-GUET', pron_fr:'ba-GUET'},
            {emoji:'🍿', es:'palomitas', en:'popcorn', fr:'pop-corn', pron_es:'pa-lo-MI-tas', pron_en:'POP-korn', pron_fr:'pop-KORN'},
            {emoji:'🥞', es:'panqueque', en:'pancake', fr:'crêpe', pron_es:'pan-KE-ke', pron_en:'PAN-keik', pron_fr:'krep'},
            {emoji:'🍩', es:'dona', en:'donut', fr:'beignet', pron_es:'DO-na', pron_en:'DOU-nat', pron_fr:'be-ÑÉ'},
            {emoji:'🧇', es:'waffle', en:'waffle', fr:'gaufre', pron_es:'UA-fle', pron_en:'UÓ-fel', pron_fr:'GOFR'},
            {emoji:'🌮', es:'taco', en:'taco', fr:'taco', pron_es:'TA-ko', pron_en:'TA-ko', pron_fr:'ta-KÓ'},
            {emoji:'🍔', es:'hamburguesa', en:'hamburger', fr:'hamburger', pron_es:'am-bur-GE-sa', pron_en:'JAM-ber-ger', pron_fr:'am-bur-GÉR'},
            {emoji:'🌭', es:'perro caliente', en:'hot dog', fr:'hot-dog', pron_es:'PE-rro ka-LIÉN-te', pron_en:'jot dog', pron_fr:'ot-DOG'},
            {emoji:'🍟', es:'papas fritas', en:'french fries', fr:'frites', pron_es:'PA-pas FRI-tas', pron_en:'french frais', pron_fr:'frit'},
            {emoji:'🥗', es:'ensalada', en:'salad', fr:'salade', pron_es:'en-sa-LA-da', pron_en:'SA-lad', pron_fr:'sa-LAD'},
            {emoji:'🍜', es:'sopa', en:'soup', fr:'soupe', pron_es:'SO-pa', pron_en:'suup', pron_fr:'sup'},
        ]
    },
    office: {
        name: { es: 'Oficina', en: 'Office', fr: 'Bureau' },
        items: [
            {emoji:'💻', es:'computadora', en:'computer', fr:'ordinateur', pron_es:'kom-pu-ta-DO-ra', pron_en:'com-PIUU-ter', pron_fr:'or-di-na-TÉR'},
            {emoji:'⌨️', es:'teclado', en:'keyboard', fr:'clavier', pron_es:'te-KLA-do', pron_en:'kíi-bord', pron_fr:'kla-VIÉ'},
            {emoji:'🖱️', es:'ratón', en:'mouse', fr:'souris', pron_es:'ra-TÓN', pron_en:'maus', pron_fr:'su-RÍ'},
            {emoji:'📱', es:'teléfono', en:'phone', fr:'téléphone', pron_es:'te-LÉ-fo-no', pron_en:'foun', pron_fr:'te-le-FON'},
            {emoji:'📎', es:'clip', en:'paperclip', fr:'trombone', pron_es:'klip', pron_en:'PEI-per-klip', pron_fr:'trom-BON'},
            {emoji:'✏️', es:'lápiz', en:'pencil', fr:'crayon', pron_es:'LÁ-pis', pron_en:'PEN-sil', pron_fr:'kre-IÓN'},
            {emoji:'📒', es:'cuaderno', en:'notebook', fr:'cahier', pron_es:'kua-DER-no', pron_en:'NOUT-buk', pron_fr:'ka-IÉ'},
            {emoji:'🖨️', es:'impresora', en:'printer', fr:'imprimante', pron_es:'im-pre-SO-ra', pron_en:'PRIN-ter', pron_fr:'im-pri-MANT'},
            // --- Muebles de oficina ---
            {emoji:'🪑', es:'silla de oficina', en:'office chair', fr:'chaise de bureau', pron_es:'SI-ya de o-fi-SI-na', pron_en:'O-fis cher', pron_fr:'shez de bü-RÓ'},
            {emoji:'🗄️', es:'escritorio', en:'desk', fr:'bureau', pron_es:'es-kri-TO-rio', pron_en:'desk', pron_fr:'bü-RÓ'},
            {emoji:'📚', es:'estante', en:'shelf', fr:'étagère', pron_es:'es-TAN-te', pron_en:'shelf', pron_fr:'e-ta-JÉR'},
            {emoji:'🗃️', es:'archivador', en:'filing cabinet', fr:'classeur', pron_es:'ar-chi-ba-DOR', pron_en:'FAI-ling KA-bi-net', pron_fr:'kla-SÉR'},
            {emoji:'🗑️', es:'papelera', en:'trash can', fr:'corbeille', pron_es:'pa-pe-LE-ra', pron_en:'trash kan', pron_fr:'kor-BEY'},
            // --- Material de escritura ---
            {emoji:'🖊️', es:'bolígrafo', en:'pen', fr:'stylo', pron_es:'bo-LÍ-gra-fo', pron_en:'pen', pron_fr:'sti-LÓ'},
            {emoji:'📝', es:'nota', en:'note', fr:'note', pron_es:'NO-ta', pron_en:'nout', pron_fr:'not'},
            {emoji:'📋', es:'portapapeles', en:'clipboard', fr:'presse-papiers', pron_es:'por-ta-pa-PE-les', pron_en:'KLIP-bord', pron_fr:'pres-pa-PIÉ'},
            {emoji:'📏', es:'regla', en:'ruler', fr:'règle', pron_es:'RE-gla', pron_en:'RUU-ler', pron_fr:'regl'},
            {emoji:'✂️', es:'tijeras', en:'scissors', fr:'ciseaux', pron_es:'ti-JE-ras', pron_en:'SI-sors', pron_fr:'si-ZÓ'},
            {emoji:'📐', es:'escuadra', en:'set square', fr:'équerre', pron_es:'es-KUA-dra', pron_en:'set skuer', pron_fr:'e-KER'},
            {emoji:'🖍️', es:'crayón', en:'crayon', fr:'crayon de couleur', pron_es:'kra-IÓN', pron_en:'KREI-on', pron_fr:'kre-IÓN de ku-LÉR'},
            {emoji:'🔏', es:'sello', en:'stamp', fr:'tampon', pron_es:'SE-yo', pron_en:'stamp', pron_fr:'tam-PÓN'},
            {emoji:'📌', es:'chincheta', en:'thumbtack', fr:'punaise', pron_es:'chin-CHE-ta', pron_en:'TAM-tak', pron_fr:'pü-NEZ'},
            {emoji:'🧷', es:'grapa', en:'staple', fr:'agrafe', pron_es:'GRA-pa', pron_en:'STEI-pel', pron_fr:'a-GRAF'},
            {emoji:'📑', es:'carpeta', en:'folder', fr:'dossier', pron_es:'kar-PE-ta', pron_en:'FOUL-der', pron_fr:'do-SIÉ'},
            {emoji:'🗂️', es:'archivo', en:'file', fr:'fichier', pron_es:'ar-CHI-bo', pron_en:'fail', pron_fr:'fi-SHIÉ'},
            {emoji:'📊', es:'gráfico', en:'chart', fr:'graphique', pron_es:'GRÁ-fi-ko', pron_en:'chart', pron_fr:'gra-FIK'},
            // --- Tecnología ---
            {emoji:'🖥️', es:'monitor', en:'monitor', fr:'écran', pron_es:'mo-ni-TOR', pron_en:'MO-ni-tor', pron_fr:'e-KRÁN'},
            {emoji:'💾', es:'disco duro', en:'hard drive', fr:'disque dur', pron_es:'DIS-ko DU-ro', pron_en:'jard draiv', pron_fr:'disk dür'},
            {emoji:'🔌', es:'enchufe', en:'plug', fr:'prise', pron_es:'en-CHU-fe', pron_en:'plag', pron_fr:'priz'},
            {emoji:'🔋', es:'batería', en:'battery', fr:'batterie', pron_es:'ba-te-RÍ-a', pron_en:'BA-te-ri', pron_fr:'ba-te-RÍ'},
            {emoji:'📡', es:'antena', en:'antenna', fr:'antenne', pron_es:'an-TE-na', pron_en:'an-TE-na', pron_fr:'an-TEN'},
            {emoji:'🎧', es:'audífonos', en:'headphones', fr:'casque', pron_es:'au-DÍ-fo-nos', pron_en:'JED-fons', pron_fr:'kask'},
            {emoji:'🎤', es:'micrófono', en:'microphone', fr:'microphone', pron_es:'mi-KRÓ-fo-no', pron_en:'MAI-kro-fon', pron_fr:'mi-kro-FON'},
            {emoji:'📷', es:'cámara', en:'camera', fr:'caméra', pron_es:'KÁ-ma-ra', pron_en:'KA-me-ra', pron_fr:'ka-me-RÁ'},
            {emoji:'💿', es:'disco', en:'disc', fr:'disque', pron_es:'DIS-ko', pron_en:'disk', pron_fr:'disk'},
            {emoji:'🖲️', es:'escáner', en:'scanner', fr:'scanner', pron_es:'es-KÁ-ner', pron_en:'SKA-ner', pron_fr:'ska-NÉR'},
            {emoji:'📠', es:'fax', en:'fax', fr:'fax', pron_es:'faks', pron_en:'faks', pron_fr:'faks'},
            // --- Accesorios ---
            {emoji:'🕶️', es:'gafas', en:'glasses', fr:'lunettes', pron_es:'GA-fas', pron_en:'GLA-ses', pron_fr:'lü-NET'},
            {emoji:'⌚', es:'reloj', en:'watch', fr:'montre', pron_es:'re-LOJ', pron_en:'uotch', pron_fr:'montr'},
            {emoji:'🎒', es:'mochila', en:'backpack', fr:'sac à dos', pron_es:'mo-CHI-la', pron_en:'BAK-pak', pron_fr:'sak a DÓ'},
            {emoji:'👜', es:'bolso', en:'bag', fr:'sac', pron_es:'BOL-so', pron_en:'bag', pron_fr:'sak'},
            {emoji:'🧳', es:'maletín', en:'briefcase', fr:'mallette', pron_es:'ma-le-TÍN', pron_en:'BRIIF-keis', pron_fr:'ma-LET'},
            {emoji:'📆', es:'calendario', en:'calendar', fr:'calendrier', pron_es:'ka-len-DA-rio', pron_en:'KA-len-dar', pron_fr:'ka-lan-DRIÉ'},
            {emoji:'🕰️', es:'reloj de pared', en:'wall clock', fr:'horloge', pron_es:'re-LOJ de pa-RED', pron_en:'uol klok', pron_fr:'or-LOSH'},
            {emoji:'💡', es:'lámpara de escritorio', en:'desk lamp', fr:'lampe de bureau', pron_es:'LÁM-pa-ra de es-kri-TO-rio', pron_en:'desk lamp', pron_fr:'lamp de bü-RÓ'},
            {emoji:'📮', es:'buzón', en:'mailbox', fr:'boîte aux lettres', pron_es:'bu-SÓN', pron_en:'MEIL-boks', pron_fr:'buat o LETR'},
            {emoji:'🔑', es:'llave', en:'key', fr:'clé', pron_es:'YA-ve', pron_en:'kii', pron_fr:'klé'},
            {emoji:'🔒', es:'candado', en:'lock', fr:'cadenas', pron_es:'kan-DA-do', pron_en:'lok', pron_fr:'ka-de-NÁ'},
            {emoji:'📐', es:'compás', en:'compass', fr:'compas', pron_es:'kom-PÁS', pron_en:'KOM-pas', pron_fr:'kom-PÁ'},
            {emoji:'🗓️', es:'agenda', en:'planner', fr:'agenda', pron_es:'a-JEN-da', pron_en:'PLA-ner', pron_fr:'a-jen-DÁ'},
            {emoji:'📃', es:'documento', en:'document', fr:'document', pron_es:'do-ku-MEN-to', pron_en:'DO-kiu-ment', pron_fr:'do-kü-MÁN'},
            {emoji:'✉️', es:'sobre', en:'envelope', fr:'enveloppe', pron_es:'SO-bre', pron_en:'EN-ve-loup', pron_fr:'an-ve-LOP'},
            {emoji:'📖', es:'libro', en:'book', fr:'livre', pron_es:'LI-bro', pron_en:'buk', pron_fr:'livr'},
            {emoji:'🗞️', es:'periódico', en:'newspaper', fr:'journal', pron_es:'pe-RIÓ-di-ko', pron_en:'NIUS-pei-per', pron_fr:'jur-NÁL'},
            {emoji:'🖼️', es:'cuadro', en:'painting', fr:'tableau', pron_es:'KUA-dro', pron_en:'PEIN-ting', pron_fr:'ta-BLÓ'},
            {emoji:'🗺️', es:'mapa', en:'map', fr:'carte', pron_es:'MA-pa', pron_en:'map', pron_fr:'kart'},
            {emoji:'🖋️', es:'pluma', en:'fountain pen', fr:'plume', pron_es:'PLU-ma', pron_en:'FAUN-tin pen', pron_fr:'plüm'},
            {emoji:'📍', es:'marcador', en:'marker', fr:'marqueur', pron_es:'mar-ka-DOR', pron_en:'MAR-ker', pron_fr:'mar-KÉR'},
            {emoji:'🔍', es:'lupa', en:'magnifying glass', fr:'loupe', pron_es:'LU-pa', pron_en:'MAG-ni-fai-ing glas', pron_fr:'lup'},
            {emoji:'🧮', es:'calculadora', en:'calculator', fr:'calculatrice', pron_es:'kal-ku-la-DO-ra', pron_en:'KAL-kiu-lei-tor', pron_fr:'kal-kü-la-TRIS'},
            {emoji:'🖇️', es:'grapadora', en:'stapler', fr:'agrafeuse', pron_es:'gra-pa-DO-ra', pron_en:'STEI-pler', pron_fr:'a-gra-FÉZ'},
            {emoji:'🏷️', es:'etiqueta', en:'label', fr:'étiquette', pron_es:'e-ti-KE-ta', pron_en:'LEI-bel', pron_fr:'e-ti-KET'},
            {emoji:'📩', es:'correo', en:'email', fr:'courriel', pron_es:'ko-RRE-o', pron_en:'II-meil', pron_fr:'ku-RIÉL'},
            {emoji:'🔗', es:'enlace', en:'link', fr:'lien', pron_es:'en-LA-se', pron_en:'link', pron_fr:'lien'},
            {emoji:'📤', es:'bandeja de salida', en:'outbox', fr:'boîte d\'envoi', pron_es:'ban-DE-ja de sa-LI-da', pron_en:'AUT-boks', pron_fr:'buat dan-VUÁ'},
            {emoji:'📥', es:'bandeja de entrada', en:'inbox', fr:'boîte de réception', pron_es:'ban-DE-ja de en-TRA-da', pron_en:'IN-boks', pron_fr:'buat de re-sep-SIÓN'},
            {emoji:'🔔', es:'notificación', en:'notification', fr:'notification', pron_es:'no-ti-fi-ka-SIÓN', pron_en:'no-ti-fi-KEI-shon', pron_fr:'no-ti-fi-ka-SIÓN'},
            {emoji:'⚙️', es:'configuración', en:'settings', fr:'paramètres', pron_es:'kon-fi-gu-ra-SIÓN', pron_en:'SE-tings', pron_fr:'pa-ra-METR'},
            {emoji:'🔊', es:'altavoz', en:'speaker', fr:'haut-parleur', pron_es:'al-ta-BOS', pron_en:'SPII-ker', pron_fr:'o-par-LÉR'},
            {emoji:'📶', es:'wifi', en:'wifi', fr:'wifi', pron_es:'UAI-fai', pron_en:'UAI-fai', pron_fr:'ui-FÍ'},
            {emoji:'💾', es:'memoria USB', en:'USB drive', fr:'clé USB', pron_es:'me-MO-ria u-ese-BE', pron_en:'iuu-es-BII draiv', pron_fr:'klé ü-es-BE'},
            // --- Más elementos de oficina ---
            {emoji:'🗃️', es:'archivador', en:'filing cabinet', fr:'classeur', pron_es:'ar-chi-ba-DOR', pron_en:'FAI-ling KA-bi-net', pron_fr:'kla-SÉR'},
            {emoji:'📆', es:'calendario', en:'calendar', fr:'calendrier', pron_es:'ka-len-DA-rio', pron_en:'KA-len-der', pron_fr:'ka-lan-DRIÉ'},
            {emoji:'🖊️', es:'bolígrafo', en:'pen', fr:'stylo', pron_es:'bo-LÍ-gra-fo', pron_en:'pen', pron_fr:'sti-LÓ'},
            {emoji:'📋', es:'portapapeles', en:'clipboard', fr:'presse-papiers', pron_es:'por-ta-pa-PE-les', pron_en:'KLIP-bord', pron_fr:'pres-pa-PIÉ'},
            {emoji:'🗑️', es:'papelera', en:'trash can', fr:'corbeille', pron_es:'pa-pe-LE-ra', pron_en:'trash kan', pron_fr:'kor-BEY'},
            {emoji:'📌', es:'chincheta', en:'thumbtack', fr:'punaise', pron_es:'chin-CHE-ta', pron_en:'ZHAM-tak', pron_fr:'pü-NEZ'},
            {emoji:'✂️', es:'tijeras', en:'scissors', fr:'ciseaux', pron_es:'ti-JE-ras', pron_en:'SI-sors', pron_fr:'si-ZÓ'},
            {emoji:'🖥️', es:'monitor', en:'monitor', fr:'moniteur', pron_es:'mo-ni-TOR', pron_en:'MO-ni-tor', pron_fr:'mo-ni-TÉR'},
            {emoji:'💡', es:'lámpara de escritorio', en:'desk lamp', fr:'lampe de bureau', pron_es:'LÁM-pa-ra de es-kri-TO-rio', pron_en:'desk lamp', pron_fr:'lamp de bü-RÓ'},
        ]
    },
    workshop: {
        name: { es: 'Taller', en: 'Workshop', fr: 'Atelier' },
        items: [
            {emoji:'🔨', es:'martillo', en:'hammer', fr:'marteau', pron_es:'mar-TI-yo', pron_en:'JA-mer', pron_fr:'mar-TÓ'},
            {emoji:'🪛', es:'destornillador', en:'screwdriver', fr:'tournevis', pron_es:'des-tor-ni-ya-DOR', pron_en:'SKRUU-drai-ver', pron_fr:'tur-ne-VÍS'},
            {emoji:'🔧', es:'llave inglesa', en:'wrench', fr:'clé', pron_es:'YA-ve in-GLE-sa', pron_en:'rench', pron_fr:'klé'},
            {emoji:'🪚', es:'sierra', en:'saw', fr:'scie', pron_es:'SIE-ra', pron_en:'so', pron_fr:'sí'},
            {emoji:'📏', es:'regla', en:'ruler', fr:'règle', pron_es:'RE-gla', pron_en:'RUU-ler', pron_fr:'regl'},
            {emoji:'🧲', es:'imán', en:'magnet', fr:'aimant', pron_es:'i-MÁN', pron_en:'MAG-net', pron_fr:'e-MÁN'},
            {emoji:'🔩', es:'tornillo', en:'screw', fr:'vis', pron_es:'tor-NI-yo', pron_en:'skruu', pron_fr:'vís'},
            {emoji:'🪣', es:'cubo', en:'bucket', fr:'seau', pron_es:'KU-bo', pron_en:'BA-ket', pron_fr:'só'},
            // --- Herramientas adicionales ---
            {emoji:'🔧', es:'alicates', en:'pliers', fr:'pinces', pron_es:'a-li-KA-tes', pron_en:'PLAI-ers', pron_fr:'pins'},
            {emoji:'🪜', es:'escalera', en:'ladder', fr:'échelle', pron_es:'es-ka-LE-ra', pron_en:'LA-der', pron_fr:'e-SHEL'},
            {emoji:'🧱', es:'ladrillo', en:'brick', fr:'brique', pron_es:'la-DRI-yo', pron_en:'brik', pron_fr:'brik'},
            {emoji:'🪵', es:'madera', en:'wood', fr:'bois', pron_es:'ma-DE-ra', pron_en:'uud', pron_fr:'buá'},
            {emoji:'⛏️', es:'pico', en:'pickaxe', fr:'pioche', pron_es:'PI-ko', pron_en:'PIK-aks', pron_fr:'piosh'},
            {emoji:'🪓', es:'hacha', en:'axe', fr:'hache', pron_es:'A-cha', pron_en:'aks', pron_fr:'ash'},
            {emoji:'🔗', es:'cadena', en:'chain', fr:'chaîne', pron_es:'ka-DE-na', pron_en:'chein', pron_fr:'shen'},
            {emoji:'🪢', es:'cuerda', en:'rope', fr:'corde', pron_es:'KUER-da', pron_en:'roup', pron_fr:'kord'},
            {emoji:'🔒', es:'candado', en:'padlock', fr:'cadenas', pron_es:'kan-DA-do', pron_en:'PAD-lok', pron_fr:'ka-de-NÁ'},
            {emoji:'⚙️', es:'engranaje', en:'gear', fr:'engrenage', pron_es:'en-gra-NA-je', pron_en:'guir', pron_fr:'an-gre-NASH'},
            {emoji:'🔌', es:'cable', en:'cable', fr:'câble', pron_es:'KA-ble', pron_en:'KEI-bel', pron_fr:'kabl'},
            {emoji:'🧲', es:'tuerca', en:'nut', fr:'écrou', pron_es:'TUER-ka', pron_en:'nat', pron_fr:'e-KRÚ'},
            {emoji:'🔩', es:'perno', en:'bolt', fr:'boulon', pron_es:'PER-no', pron_en:'boult', pron_fr:'bu-LÓN'},
            {emoji:'🪤', es:'trampa', en:'trap', fr:'piège', pron_es:'TRAM-pa', pron_en:'trap', pron_fr:'piézh'},
            {emoji:'🧰', es:'caja de herramientas', en:'toolbox', fr:'boîte à outils', pron_es:'KA-ja de e-rra-MIÉN-tas', pron_en:'TUUL-boks', pron_fr:'buat a u-TÍ'},
            {emoji:'🪠', es:'desatascador', en:'plunger', fr:'ventouse', pron_es:'de-sa-tas-ka-DOR', pron_en:'PLAN-yer', pron_fr:'van-TÚZ'},
            {emoji:'🧹', es:'escoba', en:'broom', fr:'balai', pron_es:'es-KO-ba', pron_en:'bruum', pron_fr:'ba-LÉ'},
            {emoji:'🧯', es:'extintor', en:'fire extinguisher', fr:'extincteur', pron_es:'eks-tin-TOR', pron_en:'FAIR iks-TIN-gui-sher', pron_fr:'eks-tink-TÉR'},
            {emoji:'🪝', es:'gancho', en:'hook', fr:'crochet', pron_es:'GAN-cho', pron_en:'juk', pron_fr:'kro-SHÉ'},
            {emoji:'📐', es:'nivel', en:'level', fr:'niveau', pron_es:'ni-BEL', pron_en:'LE-vel', pron_fr:'ni-VÓ'},
            {emoji:'🖌️', es:'brocha', en:'paintbrush', fr:'pinceau', pron_es:'BRO-cha', pron_en:'PEINT-brush', pron_fr:'pin-SÓ'},
            {emoji:'🎨', es:'pintura', en:'paint', fr:'peinture', pron_es:'pin-TU-ra', pron_en:'peint', pron_fr:'pen-TÜR'},
            {emoji:'🪨', es:'piedra', en:'stone', fr:'pierre', pron_es:'PIE-dra', pron_en:'stoun', pron_fr:'pier'},
            {emoji:'⚒️', es:'cincel', en:'chisel', fr:'ciseau', pron_es:'sin-SEL', pron_en:'CHI-zel', pron_fr:'si-ZÓ'},
            {emoji:'🏗️', es:'grúa', en:'crane', fr:'grue', pron_es:'GRÚ-a', pron_en:'krein', pron_fr:'grü'},
            {emoji:'🚧', es:'barrera', en:'barrier', fr:'barrière', pron_es:'ba-RRE-ra', pron_en:'BA-ri-er', pron_fr:'ba-RIÉR'},
            {emoji:'🧪', es:'tubo de ensayo', en:'test tube', fr:'tube à essai', pron_es:'TU-bo de en-SA-yo', pron_en:'test tiub', pron_fr:'tüb a e-SÉ'},
            {emoji:'⚡', es:'electricidad', en:'electricity', fr:'électricité', pron_es:'e-lek-tri-si-DÁD', pron_en:'i-lek-TRI-si-ti', pron_fr:'e-lek-tri-si-TÉ'},
            {emoji:'💡', es:'bombilla', en:'light bulb', fr:'ampoule', pron_es:'bom-BI-ya', pron_en:'lait balb', pron_fr:'am-PUL'},
            {emoji:'🔦', es:'linterna', en:'flashlight', fr:'lampe torche', pron_es:'lin-TER-na', pron_en:'FLASH-lait', pron_fr:'lamp torsh'},
            {emoji:'🧰', es:'taladro', en:'drill', fr:'perceuse', pron_es:'ta-LA-dro', pron_en:'dril', pron_fr:'per-SÉZ'},
            {emoji:'🔧', es:'llave de tubo', en:'pipe wrench', fr:'clé à tube', pron_es:'YA-ve de TU-bo', pron_en:'paip rench', pron_fr:'klé a tüb'},
            {emoji:'🪵', es:'tablón', en:'plank', fr:'planche', pron_es:'ta-BLÓN', pron_en:'plank', pron_fr:'plansh'},
            {emoji:'🏠', es:'cemento', en:'cement', fr:'ciment', pron_es:'se-MEN-to', pron_en:'si-MENT', pron_fr:'si-MÁN'},
            {emoji:'🧱', es:'arena', en:'sand', fr:'sable', pron_es:'a-RE-na', pron_en:'sand', pron_fr:'sabl'},
            {emoji:'🪣', es:'pala', en:'shovel', fr:'pelle', pron_es:'PA-la', pron_en:'SHA-vel', pron_fr:'pel'},
            {emoji:'🌡️', es:'termómetro', en:'thermometer', fr:'thermomètre', pron_es:'ter-MÓ-me-tro', pron_en:'ter-MO-me-ter', pron_fr:'ter-mo-METR'},
            {emoji:'⚖️', es:'balanza', en:'scale', fr:'balance', pron_es:'ba-LAN-sa', pron_en:'skeil', pron_fr:'ba-LÁNS'},
            {emoji:'🧲', es:'cinta adhesiva', en:'tape', fr:'ruban adhésif', pron_es:'SIN-ta ad-e-SI-ba', pron_en:'teip', pron_fr:'rü-BÁN ad-e-SIF'},
            {emoji:'🪞', es:'lija', en:'sandpaper', fr:'papier de verre', pron_es:'LI-ja', pron_en:'SAND-pei-per', pron_fr:'pa-PIÉ de VER'},
            {emoji:'🔋', es:'pila', en:'battery', fr:'pile', pron_es:'PI-la', pron_en:'BA-te-ri', pron_fr:'pil'},
            {emoji:'💧', es:'grifo', en:'faucet', fr:'robinet', pron_es:'GRI-fo', pron_en:'FO-set', pron_fr:'ro-bi-NÉ'},
            {emoji:'🚿', es:'ducha', en:'shower', fr:'douche', pron_es:'DU-cha', pron_en:'SHA-uer', pron_fr:'dush'},
            {emoji:'🪟', es:'vidrio', en:'glass', fr:'verre', pron_es:'BI-drio', pron_en:'glas', pron_fr:'ver'},
            {emoji:'🧱', es:'azulejo', en:'tile', fr:'carreau', pron_es:'a-su-LE-jo', pron_en:'tail', pron_fr:'ka-RÓ'},
            {emoji:'🏗️', es:'andamio', en:'scaffold', fr:'échafaudage', pron_es:'an-DA-mio', pron_en:'SKA-fold', pron_fr:'e-sha-fo-DASH'},
            {emoji:'🔐', es:'cerradura', en:'lock', fr:'serrure', pron_es:'se-rra-DU-ra', pron_en:'lok', pron_fr:'se-RÜR'},
            {emoji:'🪛', es:'broca', en:'drill bit', fr:'foret', pron_es:'BRO-ka', pron_en:'dril bit', pron_fr:'fo-RÉ'},
            {emoji:'🧱', es:'mosaico', en:'mosaic', fr:'mosaïque', pron_es:'mo-SAI-ko', pron_en:'mo-ZEI-ik', pron_fr:'mo-za-ÍK'},
            {emoji:'🚰', es:'tubería', en:'pipe', fr:'tuyau', pron_es:'tu-be-RÍ-a', pron_en:'paip', pron_fr:'tui-IÓ'},
            {emoji:'🔧', es:'llave allen', en:'allen wrench', fr:'clé allen', pron_es:'YA-ve A-len', pron_en:'A-len rench', pron_fr:'klé a-LEN'},
            {emoji:'🧰', es:'sierra circular', en:'circular saw', fr:'scie circulaire', pron_es:'SIE-ra sir-ku-LAR', pron_en:'SER-kiu-lar so', pron_fr:'sí sir-kü-LER'},
            {emoji:'🪨', es:'grava', en:'gravel', fr:'gravier', pron_es:'GRA-ba', pron_en:'GRA-vel', pron_fr:'gra-VIÉ'},
            {emoji:'🏚️', es:'viga', en:'beam', fr:'poutre', pron_es:'BI-ga', pron_en:'biim', pron_fr:'putr'},
            {emoji:'🪵', es:'contrachapado', en:'plywood', fr:'contreplaqué', pron_es:'kon-tra-cha-PA-do', pron_en:'PLAI-uud', pron_fr:'kontr-pla-KÉ'},
            {emoji:'🔩', es:'arandela', en:'washer', fr:'rondelle', pron_es:'a-ran-DE-la', pron_en:'UO-sher', pron_fr:'ron-DEL'},
            {emoji:'🛠️', es:'herramienta', en:'tool', fr:'outil', pron_es:'e-rra-MIÉN-ta', pron_en:'tuul', pron_fr:'u-TÍ'},
            {emoji:'🪵', es:'barniz', en:'varnish', fr:'vernis', pron_es:'bar-NÍS', pron_en:'VAR-nish', pron_fr:'ver-NÍ'},
            {emoji:'🎨', es:'rodillo', en:'roller', fr:'rouleau', pron_es:'ro-DI-yo', pron_en:'ROU-ler', pron_fr:'ru-LÓ'},
            {emoji:'🔧', es:'llave de paso', en:'valve', fr:'vanne', pron_es:'YA-ve de PA-so', pron_en:'valv', pron_fr:'van'},
            {emoji:'⛓️', es:'eslabón', en:'chain link', fr:'maillon', pron_es:'es-la-BÓN', pron_en:'chein link', pron_fr:'ma-IÓN'},
            {emoji:'🪜', es:'rampa', en:'ramp', fr:'rampe', pron_es:'RAM-pa', pron_en:'ramp', pron_fr:'ramp'},
            {emoji:'🪤', es:'resorte', en:'spring', fr:'ressort', pron_es:'re-SOR-te', pron_en:'spring', pron_fr:'re-SOR'},
            {emoji:'⚙️', es:'polea', en:'pulley', fr:'poulie', pron_es:'po-LE-a', pron_en:'PU-li', pron_fr:'pu-LÍ'},
            {emoji:'🧲', es:'abrazadera', en:'clamp', fr:'serre-joint', pron_es:'a-bra-sa-DE-ra', pron_en:'klamp', pron_fr:'ser-JUÁN'},
            {emoji:'🔧', es:'llave de cruz', en:'lug wrench', fr:'clé en croix', pron_es:'YA-ve de krus', pron_en:'lag rench', pron_fr:'klé an KRUÁ'},
            {emoji:'🪵', es:'astilla', en:'splinter', fr:'éclat', pron_es:'as-TI-ya', pron_en:'SPLIN-ter', pron_fr:'e-KLÁ'},
            {emoji:'🧪', es:'pegamento', en:'glue', fr:'colle', pron_es:'pe-ga-MEN-to', pron_en:'gluu', pron_fr:'kol'},
            {emoji:'🔩', es:'clavo', en:'nail', fr:'clou', pron_es:'KLA-bo', pron_en:'neil', pron_fr:'klu'},
            {emoji:'📐', es:'cinta métrica', en:'measuring tape', fr:'mètre ruban', pron_es:'SIN-ta ME-tri-ka', pron_en:'ME-shu-ring teip', pron_fr:'metr rü-BÁN'},
            {emoji:'🛠️', es:'taladro', en:'drill', fr:'perceuse', pron_es:'ta-LA-dro', pron_en:'dril', pron_fr:'per-SÉZ'},
            {emoji:'🔦', es:'linterna', en:'flashlight', fr:'lampe de poche', pron_es:'lin-TER-na', pron_en:'FLASH-lait', pron_fr:'lamp de posh'},
        ]
    },
    home: {
        name: { es: 'Hogar', en: 'Home', fr: 'Maison' },
        items: [
            {emoji:'🛋️', es:'sofá', en:'sofa', fr:'canapé', pron_es:'so-FÁ', pron_en:'SOU-fa', pron_fr:'ka-na-PÉ'},
            {emoji:'🪑', es:'silla', en:'chair', fr:'chaise', pron_es:'SI-ya', pron_en:'cher', pron_fr:'shez'},
            {emoji:'🛏️', es:'cama', en:'bed', fr:'lit', pron_es:'KA-ma', pron_en:'bed', pron_fr:'lí'},
            {emoji:'🪟', es:'ventana', en:'window', fr:'fenêtre', pron_es:'ben-TA-na', pron_en:'UÍN-dou', pron_fr:'fe-NÉTR'},
            {emoji:'🚪', es:'puerta', en:'door', fr:'porte', pron_es:'PUER-ta', pron_en:'dor', pron_fr:'port'},
            {emoji:'💡', es:'lámpara', en:'lamp', fr:'lampe', pron_es:'LÁM-pa-ra', pron_en:'lamp', pron_fr:'lamp'},
            {emoji:'📺', es:'televisor', en:'television', fr:'télévision', pron_es:'te-le-vi-SOR', pron_en:'TEL-e-vi-shon', pron_fr:'te-le-vi-SIÓN'},
            {emoji:'🪞', es:'espejo', en:'mirror', fr:'miroir', pron_es:'es-PE-jo', pron_en:'MÍ-ror', pron_fr:'mi-RUÁR'},
            // --- Más muebles y partes de la casa ---
            {emoji:'🏠', es:'casa', en:'house', fr:'maison', pron_es:'KA-sa', pron_en:'jaus', pron_fr:'me-ZÓN'},
            {emoji:'🏢', es:'edificio', en:'building', fr:'bâtiment', pron_es:'e-di-FI-sio', pron_en:'BIL-ding', pron_fr:'ba-ti-MÁN'},
            {emoji:'🏡', es:'jardín', en:'garden', fr:'jardin', pron_es:'jar-DÍN', pron_en:'GAR-den', pron_fr:'jar-DÉN'},
            {emoji:'🧱', es:'pared', en:'wall', fr:'mur', pron_es:'pa-RED', pron_en:'uol', pron_fr:'mür'},
            {emoji:'🏠', es:'techo', en:'roof', fr:'toit', pron_es:'TE-cho', pron_en:'ruuf', pron_fr:'tuá'},
            {emoji:'🪜', es:'escalera', en:'stairs', fr:'escalier', pron_es:'es-ka-LE-ra', pron_en:'sters', pron_fr:'es-ka-LIÉ'},
            {emoji:'🛁', es:'bañera', en:'bathtub', fr:'baignoire', pron_es:'ba-ÑE-ra', pron_en:'BAZ-tab', pron_fr:'be-NUÁR'},
            {emoji:'🚿', es:'ducha', en:'shower', fr:'douche', pron_es:'DU-cha', pron_en:'SHA-uer', pron_fr:'dush'},
            {emoji:'🚽', es:'inodoro', en:'toilet', fr:'toilettes', pron_es:'i-no-DO-ro', pron_en:'TOI-let', pron_fr:'tua-LET'},
            {emoji:'🪥', es:'cepillo de dientes', en:'toothbrush', fr:'brosse à dents', pron_es:'se-PI-yo de DIÉN-tes', pron_en:'TUUZ-brush', pron_fr:'bros a DÁN'},
            {emoji:'🧴', es:'jabón', en:'soap', fr:'savon', pron_es:'ja-BÓN', pron_en:'soup', pron_fr:'sa-VÓN'},
            {emoji:'🧻', es:'papel higiénico', en:'toilet paper', fr:'papier toilette', pron_es:'pa-PEL i-JIÉ-ni-ko', pron_en:'TOI-let PEI-per', pron_fr:'pa-PIÉ tua-LET'},
            {emoji:'🪣', es:'cubo de basura', en:'trash bin', fr:'poubelle', pron_es:'KU-bo de ba-SU-ra', pron_en:'trash bin', pron_fr:'pu-BEL'},
            {emoji:'🧹', es:'aspiradora', en:'vacuum cleaner', fr:'aspirateur', pron_es:'as-pi-ra-DO-ra', pron_en:'VA-kiuum KLII-ner', pron_fr:'as-pi-ra-TÉR'},
            {emoji:'🧺', es:'cesta', en:'basket', fr:'panier', pron_es:'SES-ta', pron_en:'BAS-ket', pron_fr:'pa-NIÉ'},
            {emoji:'🛏️', es:'almohada', en:'pillow', fr:'oreiller', pron_es:'al-mo-A-da', pron_en:'PI-lou', pron_fr:'o-re-IÉ'},
            {emoji:'🛏️', es:'sábana', en:'sheet', fr:'drap', pron_es:'SÁ-ba-na', pron_en:'shiit', pron_fr:'dra'},
            {emoji:'🧶', es:'manta', en:'blanket', fr:'couverture', pron_es:'MAN-ta', pron_en:'BLAN-ket', pron_fr:'ku-ver-TÜR'},
            {emoji:'🪟', es:'cortina', en:'curtain', fr:'rideau', pron_es:'kor-TI-na', pron_en:'KER-ten', pron_fr:'ri-DÓ'},
            {emoji:'🖼️', es:'cuadro', en:'painting', fr:'tableau', pron_es:'KUA-dro', pron_en:'PEIN-ting', pron_fr:'ta-BLÓ'},
            {emoji:'🪴', es:'planta', en:'plant', fr:'plante', pron_es:'PLAN-ta', pron_en:'plant', pron_fr:'plant'},
            {emoji:'🌸', es:'flor', en:'flower', fr:'fleur', pron_es:'flor', pron_en:'FLAU-er', pron_fr:'fler'},
            {emoji:'🕯️', es:'vela', en:'candle', fr:'bougie', pron_es:'BE-la', pron_en:'KAN-del', pron_fr:'bu-JÍ'},
            {emoji:'🗝️', es:'llave', en:'key', fr:'clé', pron_es:'YA-ve', pron_en:'kii', pron_fr:'klé'},
            {emoji:'🔔', es:'timbre', en:'doorbell', fr:'sonnette', pron_es:'TIM-bre', pron_en:'DOR-bel', pron_fr:'so-NET'},
            {emoji:'📻', es:'radio', en:'radio', fr:'radio', pron_es:'RA-dio', pron_en:'REI-dio', pron_fr:'ra-DIÓ'},
            {emoji:'🧲', es:'imán', en:'magnet', fr:'aimant', pron_es:'i-MÁN', pron_en:'MAG-net', pron_fr:'e-MÁN'},
            {emoji:'🌡️', es:'termómetro', en:'thermometer', fr:'thermomètre', pron_es:'ter-MÓ-me-tro', pron_en:'ter-MO-me-ter', pron_fr:'ter-mo-METR'},
            // --- Ropa y textiles ---
            {emoji:'👕', es:'camiseta', en:'t-shirt', fr:'t-shirt', pron_es:'ka-mi-SE-ta', pron_en:'tii-shert', pron_fr:'tii-shert'},
            {emoji:'👖', es:'pantalón', en:'pants', fr:'pantalon', pron_es:'pan-ta-LÓN', pron_en:'pants', pron_fr:'pan-ta-LÓN'},
            {emoji:'👗', es:'vestido', en:'dress', fr:'robe', pron_es:'bes-TI-do', pron_en:'dres', pron_fr:'rob'},
            {emoji:'🧥', es:'abrigo', en:'coat', fr:'manteau', pron_es:'a-BRI-go', pron_en:'kout', pron_fr:'man-TÓ'},
            {emoji:'👟', es:'zapato', en:'shoe', fr:'chaussure', pron_es:'sa-PA-to', pron_en:'shuu', pron_fr:'sho-SÜR'},
            {emoji:'🧦', es:'calcetín', en:'sock', fr:'chaussette', pron_es:'kal-se-TÍN', pron_en:'sok', pron_fr:'sho-SET'},
            {emoji:'🧣', es:'bufanda', en:'scarf', fr:'écharpe', pron_es:'bu-FAN-da', pron_en:'skarf', pron_fr:'e-SHARP'},
            {emoji:'🧤', es:'guante', en:'glove', fr:'gant', pron_es:'GUAN-te', pron_en:'glav', pron_fr:'gán'},
            {emoji:'👒', es:'sombrero', en:'hat', fr:'chapeau', pron_es:'som-BRE-ro', pron_en:'jat', pron_fr:'sha-PÓ'},
            {emoji:'🧢', es:'gorra', en:'cap', fr:'casquette', pron_es:'GO-rra', pron_en:'kap', pron_fr:'kas-KET'},
            {emoji:'👓', es:'gafas', en:'glasses', fr:'lunettes', pron_es:'GA-fas', pron_en:'GLA-ses', pron_fr:'lü-NET'},
            {emoji:'💍', es:'anillo', en:'ring', fr:'bague', pron_es:'a-NI-yo', pron_en:'ring', pron_fr:'bag'},
            {emoji:'⌚', es:'reloj', en:'watch', fr:'montre', pron_es:'re-LOJ', pron_en:'uotch', pron_fr:'montr'},
            {emoji:'☂️', es:'paraguas', en:'umbrella', fr:'parapluie', pron_es:'pa-RA-guas', pron_en:'am-BRE-la', pron_fr:'pa-ra-PLÜÍ'},
            // --- Comidas del hogar ---
            {emoji:'🍳', es:'desayuno', en:'breakfast', fr:'petit déjeuner', pron_es:'de-sa-YU-no', pron_en:'BREK-fast', pron_fr:'pe-TÍ de-je-NÉ'},
            {emoji:'🥗', es:'almuerzo', en:'lunch', fr:'déjeuner', pron_es:'al-MUER-so', pron_en:'lanch', pron_fr:'de-je-NÉ'},
            {emoji:'🍽️', es:'cena', en:'dinner', fr:'dîner', pron_es:'SE-na', pron_en:'DI-ner', pron_fr:'di-NÉ'},
            // --- Objetos del hogar ---
            {emoji:'🧸', es:'peluche', en:'stuffed animal', fr:'peluche', pron_es:'pe-LU-che', pron_en:'staft A-ni-mal', pron_fr:'pe-LÜSH'},
            {emoji:'🎮', es:'videojuego', en:'video game', fr:'jeu vidéo', pron_es:'bi-de-o-JUE-go', pron_en:'VI-deo geim', pron_fr:'jé vi-de-Ó'},
            {emoji:'📚', es:'estantería', en:'bookshelf', fr:'bibliothèque', pron_es:'es-tan-te-RÍ-a', pron_en:'BUK-shelf', pron_fr:'bi-blio-TEK'},
            {emoji:'🧲', es:'alfombra', en:'carpet', fr:'tapis', pron_es:'al-FOM-bra', pron_en:'KAR-pet', pron_fr:'ta-PÍ'},
            {emoji:'🪑', es:'mesa', en:'table', fr:'table', pron_es:'ME-sa', pron_en:'TEI-bel', pron_fr:'tabl'},
            {emoji:'🍽️', es:'comedor', en:'dining room', fr:'salle à manger', pron_es:'ko-me-DOR', pron_en:'DAI-ning ruum', pron_fr:'sal a man-JÉ'},
            {emoji:'🛋️', es:'sala', en:'living room', fr:'salon', pron_es:'SA-la', pron_en:'LI-ving ruum', pron_fr:'sa-LÓN'},
            {emoji:'🛏️', es:'dormitorio', en:'bedroom', fr:'chambre', pron_es:'dor-mi-TO-rio', pron_en:'BED-ruum', pron_fr:'shambr'},
            {emoji:'🍳', es:'cocina', en:'kitchen', fr:'cuisine', pron_es:'ko-SI-na', pron_en:'KI-chen', pron_fr:'küi-ZIN'},
            {emoji:'🚿', es:'baño', en:'bathroom', fr:'salle de bain', pron_es:'BA-ño', pron_en:'BAZ-ruum', pron_fr:'sal de BÉN'},
            {emoji:'🏡', es:'garaje', en:'garage', fr:'garage', pron_es:'ga-RA-je', pron_en:'ga-RASH', pron_fr:'ga-RASH'},
            {emoji:'🪜', es:'ático', en:'attic', fr:'grenier', pron_es:'Á-ti-ko', pron_en:'A-tik', pron_fr:'gre-NIÉ'},
            {emoji:'🏚️', es:'sótano', en:'basement', fr:'sous-sol', pron_es:'SÓ-ta-no', pron_en:'BEIS-ment', pron_fr:'su-SOL'},
            {emoji:'🌳', es:'árbol', en:'tree', fr:'arbre', pron_es:'ÁR-bol', pron_en:'trii', pron_fr:'arbr'},
            {emoji:'🌻', es:'girasol', en:'sunflower', fr:'tournesol', pron_es:'ji-ra-SOL', pron_en:'SAN-flau-er', pron_fr:'tur-ne-SOL'},
            {emoji:'🐕', es:'perro', en:'dog', fr:'chien', pron_es:'PE-rro', pron_en:'dog', pron_fr:'shién'},
            {emoji:'🐈', es:'gato', en:'cat', fr:'chat', pron_es:'GA-to', pron_en:'kat', pron_fr:'shá'},
            {emoji:'🐟', es:'pez', en:'fish', fr:'poisson', pron_es:'pes', pron_en:'fish', pron_fr:'pua-SÓN'},
            {emoji:'🐦', es:'pájaro', en:'bird', fr:'oiseau', pron_es:'PÁ-ja-ro', pron_en:'berd', pron_fr:'ua-ZÓ'},
            {emoji:'🌙', es:'luna', en:'moon', fr:'lune', pron_es:'LU-na', pron_en:'muun', pron_fr:'lün'},
            {emoji:'☀️', es:'sol', en:'sun', fr:'soleil', pron_es:'sol', pron_en:'san', pron_fr:'so-LEY'},
            {emoji:'⭐', es:'estrella', en:'star', fr:'étoile', pron_es:'es-TRE-ya', pron_en:'star', pron_fr:'e-TUAL'},
            {emoji:'🌈', es:'arcoíris', en:'rainbow', fr:'arc-en-ciel', pron_es:'ar-ko-Í-ris', pron_en:'REIN-bou', pron_fr:'ark-an-SIÉL'},
            {emoji:'☁️', es:'nube', en:'cloud', fr:'nuage', pron_es:'NU-be', pron_en:'klaud', pron_fr:'nü-ÁASH'},
            {emoji:'🌧️', es:'lluvia', en:'rain', fr:'pluie', pron_es:'YU-via', pron_en:'rein', pron_fr:'plüí'},
            {emoji:'❄️', es:'nieve', en:'snow', fr:'neige', pron_es:'NIE-ve', pron_en:'snou', pron_fr:'nesh'},
            {emoji:'🔑', es:'llave', en:'key', fr:'clé', pron_es:'YA-ve', pron_en:'kii', pron_fr:'klé'},
        ]
    }
};

// ========== SINÓNIMOS PARA VALIDACIÓN FLEXIBLE ==========
// Se generan automáticamente a partir de categoryData
function buildSynonyms() {
    const syns = { es: {}, en: {}, fr: {} };

    // Manual synonyms for common words (accent-free variants + alternative names)
    const manualSyns = {
        es: {
            'cuchillo': ['cuchillo'],
            'sartén': ['sarten', 'sartén'],
            'tetera': ['tetera'],
            'computadora': ['computadora', 'computador', 'ordenador', 'pc'],
            'ratón': ['raton', 'ratón', 'mouse'],
            'teléfono': ['telefono', 'teléfono', 'celular', 'móvil', 'movil'],
            'lápiz': ['lapiz', 'lápiz'],
            'cuaderno': ['cuaderno', 'libreta'],
            'destornillador': ['destornillador', 'desarmador'],
            'sierra': ['sierra', 'serrucho'],
            'imán': ['iman', 'imán'],
            'sofá': ['sofa', 'sofá', 'sillón', 'sillon'],
            'lámpara': ['lampara', 'lámpara'],
            'televisor': ['televisor', 'television', 'televisión', 'tele', 'tv'],
            'refrigerador': ['refrigerador', 'refri', 'nevera', 'frigorífico', 'frigorifico'],
            'tazón': ['tazon', 'tazón', 'bowl'],
            'cacerola': ['cacerola', 'cazo'],
            'licuadora': ['licuadora', 'batidora'],
            'microondas': ['microondas', 'micro'],
            'zanahoria': ['zanahoria'],
            'champiñón': ['champiñon', 'champiñón', 'hongo', 'seta'],
            'plátano': ['platano', 'plátano', 'banana', 'banano'],
            'sandía': ['sandia', 'sandía'],
            'aguacate': ['aguacate', 'palta'],
            'piña': ['piña', 'pina', 'ananas', 'ananás'],
            'maíz': ['maiz', 'maíz', 'elote', 'choclo'],
            'brócoli': ['brocoli', 'brócoli'],
            'limón': ['limon', 'limón'],
            'papas fritas': ['papas fritas', 'patatas fritas', 'french fries'],
            'papa': ['papa', 'patata'],
            'cacahuate': ['cacahuate', 'cacahuete', 'maní', 'mani'],
            'panqueque': ['panqueque', 'pancake', 'hotcake', 'crepa'],
            'dona': ['dona', 'rosquilla', 'donut', 'doughnut'],
            'perro caliente': ['perro caliente', 'hot dog', 'hotdog'],
            'hamburguesa': ['hamburguesa'],
            'ensalada': ['ensalada'],
            'helado': ['helado'],
            'galleta': ['galleta'],
            'magdalena': ['magdalena', 'muffin', 'panquecito'],
            'desayuno': ['desayuno'],
            'almuerzo': ['almuerzo', 'comida'],
            'cena': ['cena'],
            'camiseta': ['camiseta', 'playera', 'remera', 'polera'],
            'pantalón': ['pantalon', 'pantalón', 'pantalones'],
            'zapato': ['zapato'],
            'calcetín': ['calcetin', 'calcetín', 'media'],
            'paraguas': ['paraguas', 'sombrilla'],
            'bañera': ['bañera', 'banera', 'tina'],
            'jabón': ['jabon', 'jabón'],
            'aspiradora': ['aspiradora'],
            'almohada': ['almohada'],
            'sábana': ['sabana', 'sábana'],
            'arcoíris': ['arcoiris', 'arcoíris'],
            'pájaro': ['pajaro', 'pájaro', 'ave'],
            'ático': ['atico', 'ático', 'desván', 'desvan'],
            'sótano': ['sotano', 'sótano'],
            'videojuego': ['videojuego', 'juego de video'],
            'estantería': ['estanteria', 'estantería', 'librero', 'librería'],
            'cortina': ['cortina'],
            'alfombra': ['alfombra', 'tapete'],
            'dormitorio': ['dormitorio', 'habitación', 'habitacion', 'cuarto', 'recámara', 'recamara'],
            'sala': ['sala', 'salón', 'salon', 'living'],
            'comedor': ['comedor'],
            'cocina': ['cocina'],
            'baño': ['baño', 'bano'],
            'llave': ['llave'],
            'bolígrafo': ['boligrafo', 'bolígrafo', 'pluma', 'lapicero', 'birome'],
            'gráfico': ['grafico', 'gráfico'],
            'audífonos': ['audifonos', 'audífonos', 'auriculares', 'cascos'],
            'micrófono': ['microfono', 'micrófono'],
            'cámara': ['camara', 'cámara'],
            'escáner': ['escaner', 'escáner'],
            'calculadora': ['calculadora'],
            'grapadora': ['grapadora', 'engrapadora'],
            'periódico': ['periodico', 'periódico', 'diario'],
            'notificación': ['notificacion', 'notificación'],
            'configuración': ['configuracion', 'configuración', 'ajustes'],
            'llave inglesa': ['llave inglesa', 'llave'],
            'escalera': ['escalera'],
            'electricidad': ['electricidad'],
            'termómetro': ['termometro', 'termómetro'],
            'tubería': ['tuberia', 'tubería', 'tubo', 'cañería', 'canería'],
            'pegamento': ['pegamento', 'cola', 'adhesivo'],
            'cinta adhesiva': ['cinta adhesiva', 'cinta', 'tape'],
            'cinta métrica': ['cinta metrica', 'cinta métrica', 'metro', 'flexómetro'],
            'girasol': ['girasol'],
            'árbol': ['arbol', 'árbol'],
        },
        en: {
            'knife': ['knife', 'cutter'],
            'fork': ['fork'],
            'spoon': ['spoon'],
            'pan': ['pan', 'frying pan', 'skillet'],
            'teapot': ['teapot', 'tea pot', 'kettle'],
            'plate': ['plate', 'dish'],
            'glass': ['glass', 'cup', 'tumbler'],
            'ice': ['ice'],
            'computer': ['computer', 'pc', 'laptop'],
            'keyboard': ['keyboard'],
            'mouse': ['mouse'],
            'phone': ['phone', 'telephone', 'cellphone', 'mobile', 'cell phone'],
            'paperclip': ['paperclip', 'paper clip', 'clip'],
            'pencil': ['pencil'],
            'notebook': ['notebook', 'note book', 'notepad'],
            'printer': ['printer'],
            'hammer': ['hammer'],
            'screwdriver': ['screwdriver', 'screw driver'],
            'wrench': ['wrench', 'spanner'],
            'saw': ['saw'],
            'ruler': ['ruler'],
            'magnet': ['magnet'],
            'screw': ['screw'],
            'bucket': ['bucket', 'pail'],
            'sofa': ['sofa', 'couch'],
            'chair': ['chair', 'seat'],
            'bed': ['bed'],
            'window': ['window'],
            'door': ['door'],
            'lamp': ['lamp', 'light'],
            'television': ['television', 'tv', 'telly'],
            'mirror': ['mirror'],
            'toaster': ['toaster'],
            'blender': ['blender', 'mixer'],
            'oven': ['oven'],
            'refrigerator': ['refrigerator', 'fridge', 'ref'],
            'microwave': ['microwave'],
            'coffee maker': ['coffee maker', 'coffeemaker', 'coffee machine'],
            'dishwasher': ['dishwasher'],
            'bowl': ['bowl'],
            'cup': ['cup', 'mug'],
            'pitcher': ['pitcher', 'jug'],
            'bottle': ['bottle'],
            'pot': ['pot'],
            'saucepan': ['saucepan', 'sauce pan'],
            'tray': ['tray'],
            'jar': ['jar'],
            'chopsticks': ['chopsticks'],
            'cutting board': ['cutting board', 'chopping board'],
            'grater': ['grater'],
            'timer': ['timer'],
            'sponge': ['sponge'],
            'napkin': ['napkin', 'serviette'],
            'butter': ['butter'],
            'salt': ['salt'],
            'pepper': ['pepper'],
            'oil': ['oil'],
            'honey': ['honey'],
            'egg': ['egg'],
            'rice': ['rice'],
            'bread': ['bread'],
            'meat': ['meat'],
            'fish': ['fish'],
            'cheese': ['cheese'],
            'carrot': ['carrot'],
            'tomato': ['tomato'],
            'onion': ['onion'],
            'potato': ['potato'],
            'lettuce': ['lettuce'],
            'lemon': ['lemon'],
            'apple': ['apple'],
            'banana': ['banana'],
            'orange': ['orange'],
            'grape': ['grape', 'grapes'],
            'strawberry': ['strawberry'],
            'watermelon': ['watermelon', 'water melon'],
            'avocado': ['avocado'],
            'pineapple': ['pineapple'],
            'coconut': ['coconut'],
            'cucumber': ['cucumber'],
            'bell pepper': ['bell pepper', 'pepper'],
            'mushroom': ['mushroom'],
            'corn': ['corn', 'maize'],
            'broccoli': ['broccoli'],
            'pasta': ['pasta', 'noodles'],
            'peanut': ['peanut'],
            'chocolate': ['chocolate'],
            'ice cream': ['ice cream', 'icecream'],
            'cake': ['cake'],
            'cookie': ['cookie', 'biscuit'],
            'milk': ['milk'],
            'coffee': ['coffee'],
            'juice': ['juice'],
            'water': ['water'],
            'tea': ['tea'],
            'muffin': ['muffin', 'cupcake'],
            'croissant': ['croissant'],
            'baguette': ['baguette'],
            'popcorn': ['popcorn', 'pop corn'],
            'pancake': ['pancake'],
            'donut': ['donut', 'doughnut'],
            'waffle': ['waffle'],
            'taco': ['taco'],
            'hamburger': ['hamburger', 'burger'],
            'hot dog': ['hot dog', 'hotdog'],
            'french fries': ['french fries', 'fries', 'chips'],
            'salad': ['salad'],
            'soup': ['soup'],
            // office extra
            'office chair': ['office chair', 'desk chair'],
            'desk': ['desk'],
            'shelf': ['shelf', 'shelves'],
            'filing cabinet': ['filing cabinet', 'file cabinet'],
            'trash can': ['trash can', 'bin', 'garbage can', 'waste bin'],
            'pen': ['pen', 'ballpoint'],
            'note': ['note'],
            'clipboard': ['clipboard'],
            'scissors': ['scissors'],
            'set square': ['set square', 'triangle ruler'],
            'crayon': ['crayon'],
            'stamp': ['stamp'],
            'thumbtack': ['thumbtack', 'push pin', 'pushpin'],
            'staple': ['staple'],
            'folder': ['folder'],
            'file': ['file'],
            'chart': ['chart', 'graph'],
            'monitor': ['monitor', 'screen', 'display'],
            'hard drive': ['hard drive', 'hard disk'],
            'plug': ['plug', 'outlet'],
            'battery': ['battery'],
            'antenna': ['antenna', 'aerial'],
            'headphones': ['headphones', 'earphones'],
            'microphone': ['microphone', 'mic'],
            'camera': ['camera'],
            'disc': ['disc', 'disk'],
            'scanner': ['scanner'],
            'fax': ['fax'],
            'glasses': ['glasses', 'spectacles', 'eyeglasses'],
            'watch': ['watch', 'wristwatch'],
            'backpack': ['backpack', 'rucksack'],
            'bag': ['bag', 'purse', 'handbag'],
            'briefcase': ['briefcase'],
            'calendar': ['calendar'],
            'wall clock': ['wall clock', 'clock'],
            'desk lamp': ['desk lamp', 'table lamp'],
            'mailbox': ['mailbox', 'mail box', 'letterbox'],
            'key': ['key'],
            'lock': ['lock', 'padlock'],
            'compass': ['compass'],
            'planner': ['planner', 'diary', 'agenda'],
            'document': ['document', 'doc'],
            'envelope': ['envelope'],
            'book': ['book'],
            'newspaper': ['newspaper', 'paper'],
            'painting': ['painting', 'picture', 'portrait'],
            'map': ['map'],
            'fountain pen': ['fountain pen'],
            'marker': ['marker', 'highlighter'],
            'magnifying glass': ['magnifying glass', 'magnifier'],
            'calculator': ['calculator'],
            'stapler': ['stapler'],
            'label': ['label', 'tag'],
            'email': ['email', 'e-mail', 'mail'],
            'link': ['link', 'url'],
            'outbox': ['outbox'],
            'inbox': ['inbox'],
            'notification': ['notification', 'alert'],
            'settings': ['settings', 'preferences', 'config'],
            'speaker': ['speaker', 'loudspeaker'],
            'wifi': ['wifi', 'wi-fi'],
            'USB drive': ['usb drive', 'flash drive', 'thumb drive', 'pen drive'],
            // workshop extra
            'pliers': ['pliers'],
            'ladder': ['ladder'],
            'brick': ['brick'],
            'wood': ['wood', 'timber', 'lumber'],
            'pickaxe': ['pickaxe', 'pick'],
            'axe': ['axe', 'ax', 'hatchet'],
            'chain': ['chain'],
            'rope': ['rope', 'cord'],
            'padlock': ['padlock', 'lock'],
            'gear': ['gear', 'cog'],
            'cable': ['cable', 'wire', 'cord'],
            'nut': ['nut'],
            'bolt': ['bolt'],
            'trap': ['trap'],
            'toolbox': ['toolbox', 'tool box'],
            'plunger': ['plunger'],
            'broom': ['broom'],
            'fire extinguisher': ['fire extinguisher', 'extinguisher'],
            'hook': ['hook'],
            'level': ['level', 'spirit level'],
            'paintbrush': ['paintbrush', 'paint brush', 'brush'],
            'paint': ['paint'],
            'stone': ['stone', 'rock'],
            'chisel': ['chisel'],
            'crane': ['crane'],
            'barrier': ['barrier', 'barricade'],
            'test tube': ['test tube'],
            'electricity': ['electricity', 'power'],
            'light bulb': ['light bulb', 'lightbulb', 'bulb'],
            'flashlight': ['flashlight', 'torch'],
            'drill': ['drill'],
            'pipe wrench': ['pipe wrench'],
            'plank': ['plank', 'board'],
            'cement': ['cement', 'concrete'],
            'sand': ['sand'],
            'shovel': ['shovel', 'spade'],
            'thermometer': ['thermometer'],
            'scale': ['scale', 'scales', 'balance'],
            'tape': ['tape', 'adhesive tape', 'duct tape'],
            'sandpaper': ['sandpaper'],
            'faucet': ['faucet', 'tap'],
            'shower': ['shower'],
            'tile': ['tile'],
            'scaffold': ['scaffold', 'scaffolding'],
            'drill bit': ['drill bit', 'bit'],
            'mosaic': ['mosaic'],
            'pipe': ['pipe', 'tube'],
            'allen wrench': ['allen wrench', 'hex wrench', 'allen key', 'hex key'],
            'circular saw': ['circular saw'],
            'gravel': ['gravel'],
            'beam': ['beam', 'rafter'],
            'plywood': ['plywood'],
            'washer': ['washer'],
            'tool': ['tool'],
            'varnish': ['varnish', 'lacquer'],
            'roller': ['roller', 'paint roller'],
            'valve': ['valve', 'stopcock'],
            'chain link': ['chain link', 'link'],
            'ramp': ['ramp'],
            'spring': ['spring', 'coil'],
            'pulley': ['pulley'],
            'clamp': ['clamp', 'vice', 'vise'],
            'lug wrench': ['lug wrench', 'tire iron'],
            'splinter': ['splinter', 'chip'],
            'glue': ['glue', 'adhesive'],
            'nail': ['nail'],
            'measuring tape': ['measuring tape', 'tape measure'],
            // home extra
            'house': ['house', 'home'],
            'building': ['building'],
            'garden': ['garden', 'yard'],
            'wall': ['wall'],
            'roof': ['roof', 'rooftop'],
            'stairs': ['stairs', 'staircase', 'steps'],
            'bathtub': ['bathtub', 'bath', 'tub'],
            'toilet': ['toilet', 'loo'],
            'toothbrush': ['toothbrush'],
            'soap': ['soap'],
            'toilet paper': ['toilet paper', 'TP'],
            'trash bin': ['trash bin', 'trash can', 'garbage can', 'dustbin'],
            'vacuum cleaner': ['vacuum cleaner', 'vacuum', 'hoover'],
            'basket': ['basket'],
            'pillow': ['pillow', 'cushion'],
            'sheet': ['sheet', 'bed sheet'],
            'blanket': ['blanket', 'comforter', 'duvet'],
            'curtain': ['curtain', 'drape', 'drapes'],
            'plant': ['plant'],
            'flower': ['flower'],
            'candle': ['candle'],
            'doorbell': ['doorbell', 'bell'],
            'radio': ['radio'],
            't-shirt': ['t-shirt', 'tshirt', 'tee', 'shirt'],
            'pants': ['pants', 'trousers'],
            'dress': ['dress', 'gown'],
            'coat': ['coat', 'jacket'],
            'shoe': ['shoe', 'sneaker'],
            'sock': ['sock', 'socks'],
            'scarf': ['scarf'],
            'glove': ['glove', 'gloves', 'mitten'],
            'hat': ['hat'],
            'cap': ['cap'],
            'ring': ['ring'],
            'umbrella': ['umbrella'],
            'breakfast': ['breakfast'],
            'lunch': ['lunch'],
            'dinner': ['dinner', 'supper'],
            'stuffed animal': ['stuffed animal', 'plush', 'plushie', 'teddy bear', 'teddy'],
            'video game': ['video game', 'videogame'],
            'bookshelf': ['bookshelf', 'book shelf'],
            'carpet': ['carpet', 'rug'],
            'table': ['table'],
            'dining room': ['dining room'],
            'living room': ['living room', 'lounge'],
            'bedroom': ['bedroom'],
            'kitchen': ['kitchen'],
            'bathroom': ['bathroom', 'restroom', 'washroom'],
            'garage': ['garage'],
            'attic': ['attic', 'loft'],
            'basement': ['basement', 'cellar'],
            'tree': ['tree'],
            'sunflower': ['sunflower'],
            'dog': ['dog', 'puppy'],
            'cat': ['cat', 'kitten'],
            'bird': ['bird'],
            'moon': ['moon'],
            'sun': ['sun'],
            'star': ['star'],
            'rainbow': ['rainbow'],
            'cloud': ['cloud'],
            'rain': ['rain'],
        },
        fr: {
            'couteau': ['couteau'],
            'fourchette': ['fourchette'],
            'cuillère': ['cuillere', 'cuillère', 'cuiller'],
            'poêle': ['poele', 'poêle'],
            'théière': ['theiere', 'théière'],
            'assiette': ['assiette'],
            'verre': ['verre'],
            'glace': ['glace'],
            'ordinateur': ['ordinateur', 'ordi', 'pc'],
            'clavier': ['clavier'],
            'souris': ['souris'],
            'téléphone': ['telephone', 'téléphone', 'tel'],
            'trombone': ['trombone'],
            'crayon': ['crayon'],
            'cahier': ['cahier'],
            'imprimante': ['imprimante'],
            'marteau': ['marteau'],
            'tournevis': ['tournevis'],
            'clé': ['cle', 'clé', 'clef'],
            'scie': ['scie'],
            'règle': ['regle', 'règle'],
            'aimant': ['aimant'],
            'vis': ['vis'],
            'seau': ['seau'],
            'canapé': ['canape', 'canapé', 'sofa'],
            'chaise': ['chaise'],
            'lit': ['lit'],
            'fenêtre': ['fenetre', 'fenêtre'],
            'porte': ['porte'],
            'lampe': ['lampe'],
            'télévision': ['television', 'télévision', 'tele', 'télé', 'tv'],
            'miroir': ['miroir'],
            'grille-pain': ['grille-pain', 'grille pain'],
            'mixeur': ['mixeur', 'blender'],
            'four': ['four'],
            'réfrigérateur': ['refrigerateur', 'réfrigérateur', 'frigo'],
            'micro-ondes': ['micro-ondes', 'micro ondes', 'micro'],
            'cafetière': ['cafetiere', 'cafetière'],
            'lave-vaisselle': ['lave-vaisselle', 'lave vaisselle'],
            'bol': ['bol'],
            'tasse': ['tasse'],
            'carafe': ['carafe'],
            'bouteille': ['bouteille'],
            'marmite': ['marmite'],
            'casserole': ['casserole'],
            'plateau': ['plateau'],
            'bocal': ['bocal'],
            'baguettes': ['baguettes'],
            'planche à découper': ['planche a decouper', 'planche à découper'],
            'râpe': ['rape', 'râpe'],
            'minuteur': ['minuteur', 'timer'],
            'éponge': ['eponge', 'éponge'],
            'serviette': ['serviette'],
            'beurre': ['beurre'],
            'sel': ['sel'],
            'poivre': ['poivre'],
            'huile': ['huile'],
            'miel': ['miel'],
            'œuf': ['oeuf', 'œuf'],
            'riz': ['riz'],
            'pain': ['pain'],
            'viande': ['viande'],
            'poisson': ['poisson'],
            'fromage': ['fromage'],
            'carotte': ['carotte'],
            'tomate': ['tomate'],
            'oignon': ['oignon', 'ognon'],
            'pomme de terre': ['pomme de terre', 'patate'],
            'laitue': ['laitue'],
            'citron': ['citron'],
            'pomme': ['pomme'],
            'banane': ['banane'],
            'orange': ['orange'],
            'raisin': ['raisin'],
            'fraise': ['fraise'],
            'pastèque': ['pasteque', 'pastèque'],
            'avocat': ['avocat'],
            'ananas': ['ananas'],
            'noix de coco': ['noix de coco', 'coco'],
            'concombre': ['concombre'],
            'poivron': ['poivron'],
            'champignon': ['champignon'],
            'maïs': ['mais', 'maïs'],
            'brocoli': ['brocoli'],
            'pâtes': ['pates', 'pâtes', 'pasta'],
            'cacahuète': ['cacahuete', 'cacahuète', 'arachide'],
            'chocolat': ['chocolat'],
            'gâteau': ['gateau', 'gâteau'],
            'biscuit': ['biscuit'],
            'lait': ['lait'],
            'café': ['cafe', 'café'],
            'jus': ['jus'],
            'eau': ['eau'],
            'thé': ['the', 'thé'],
            'muffin': ['muffin'],
            'croissant': ['croissant'],
            'baguette': ['baguette'],
            'pop-corn': ['pop-corn', 'popcorn'],
            'crêpe': ['crepe', 'crêpe'],
            'beignet': ['beignet'],
            'gaufre': ['gaufre'],
            'taco': ['taco'],
            'hamburger': ['hamburger', 'burger'],
            'hot-dog': ['hot-dog', 'hot dog', 'hotdog'],
            'frites': ['frites'],
            'salade': ['salade'],
            'soupe': ['soupe'],
            // office extra
            'chaise de bureau': ['chaise de bureau'],
            'bureau': ['bureau'],
            'étagère': ['etagere', 'étagère'],
            'classeur': ['classeur'],
            'corbeille': ['corbeille', 'poubelle'],
            'stylo': ['stylo'],
            'note': ['note'],
            'presse-papiers': ['presse-papiers', 'presse papiers'],
            'ciseaux': ['ciseaux'],
            'équerre': ['equerre', 'équerre'],
            'crayon de couleur': ['crayon de couleur'],
            'tampon': ['tampon'],
            'punaise': ['punaise'],
            'agrafe': ['agrafe'],
            'dossier': ['dossier'],
            'fichier': ['fichier'],
            'graphique': ['graphique'],
            'écran': ['ecran', 'écran', 'moniteur'],
            'disque dur': ['disque dur'],
            'prise': ['prise'],
            'batterie': ['batterie'],
            'antenne': ['antenne'],
            'casque': ['casque', 'ecouteurs', 'écouteurs'],
            'microphone': ['microphone', 'micro'],
            'caméra': ['camera', 'caméra'],
            'disque': ['disque'],
            'scanner': ['scanner'],
            'fax': ['fax'],
            'lunettes': ['lunettes'],
            'montre': ['montre'],
            'sac à dos': ['sac a dos', 'sac à dos'],
            'sac': ['sac'],
            'mallette': ['mallette', 'malette'],
            'calendrier': ['calendrier'],
            'horloge': ['horloge'],
            'lampe de bureau': ['lampe de bureau'],
            'boîte aux lettres': ['boite aux lettres', 'boîte aux lettres'],
            'cadenas': ['cadenas'],
            'compas': ['compas'],
            'agenda': ['agenda'],
            'document': ['document'],
            'enveloppe': ['enveloppe'],
            'livre': ['livre', 'bouquin'],
            'journal': ['journal'],
            'tableau': ['tableau'],
            'carte': ['carte', 'plan'],
            'plume': ['plume'],
            'marqueur': ['marqueur'],
            'loupe': ['loupe'],
            'calculatrice': ['calculatrice'],
            'agrafeuse': ['agrafeuse'],
            'étiquette': ['etiquette', 'étiquette'],
            'courriel': ['courriel', 'email', 'e-mail'],
            'lien': ['lien'],
            "boîte d'envoi": ["boite d'envoi", "boîte d'envoi"],
            'boîte de réception': ['boite de reception', 'boîte de réception'],
            'notification': ['notification'],
            'paramètres': ['parametres', 'paramètres'],
            'haut-parleur': ['haut-parleur', 'haut parleur'],
            'wifi': ['wifi', 'wi-fi'],
            'clé USB': ['cle usb', 'clé usb'],
            // workshop extra
            'pinces': ['pinces', 'pince'],
            'échelle': ['echelle', 'échelle'],
            'brique': ['brique'],
            'bois': ['bois'],
            'pioche': ['pioche'],
            'hache': ['hache'],
            'chaîne': ['chaine', 'chaîne'],
            'corde': ['corde'],
            'engrenage': ['engrenage'],
            'câble': ['cable', 'câble'],
            'écrou': ['ecrou', 'écrou'],
            'boulon': ['boulon'],
            'piège': ['piege', 'piège'],
            'boîte à outils': ['boite a outils', 'boîte à outils'],
            'ventouse': ['ventouse'],
            'balai': ['balai'],
            'extincteur': ['extincteur'],
            'crochet': ['crochet'],
            'niveau': ['niveau'],
            'pinceau': ['pinceau'],
            'peinture': ['peinture'],
            'pierre': ['pierre'],
            'ciseau': ['ciseau'],
            'grue': ['grue'],
            'barrière': ['barriere', 'barrière'],
            'tube à essai': ['tube a essai', 'tube à essai'],
            'électricité': ['electricite', 'électricité'],
            'ampoule': ['ampoule'],
            'lampe torche': ['lampe torche'],
            'perceuse': ['perceuse'],
            'clé à tube': ['cle a tube', 'clé à tube'],
            'planche': ['planche'],
            'ciment': ['ciment'],
            'sable': ['sable'],
            'pelle': ['pelle'],
            'thermomètre': ['thermometre', 'thermomètre'],
            'balance': ['balance'],
            'ruban adhésif': ['ruban adhesif', 'ruban adhésif', 'scotch'],
            'papier de verre': ['papier de verre'],
            'pile': ['pile'],
            'robinet': ['robinet'],
            'douche': ['douche'],
            'carreau': ['carreau'],
            'échafaudage': ['echafaudage', 'échafaudage'],
            'serrure': ['serrure'],
            'foret': ['foret'],
            'mosaïque': ['mosaique', 'mosaïque'],
            'tuyau': ['tuyau'],
            'clé allen': ['cle allen', 'clé allen'],
            'scie circulaire': ['scie circulaire'],
            'gravier': ['gravier'],
            'poutre': ['poutre'],
            'contreplaqué': ['contreplaque', 'contreplaqué'],
            'rondelle': ['rondelle'],
            'outil': ['outil'],
            'vernis': ['vernis'],
            'rouleau': ['rouleau'],
            'vanne': ['vanne'],
            'maillon': ['maillon'],
            'rampe': ['rampe'],
            'ressort': ['ressort'],
            'poulie': ['poulie'],
            'serre-joint': ['serre-joint', 'serre joint'],
            'clé en croix': ['cle en croix', 'clé en croix'],
            'éclat': ['eclat', 'éclat'],
            'colle': ['colle'],
            'clou': ['clou'],
            'mètre ruban': ['metre ruban', 'mètre ruban'],
            // home extra
            'maison': ['maison'],
            'bâtiment': ['batiment', 'bâtiment', 'immeuble'],
            'jardin': ['jardin'],
            'mur': ['mur'],
            'toit': ['toit'],
            'escalier': ['escalier'],
            'baignoire': ['baignoire'],
            'toilettes': ['toilettes', 'wc'],
            'brosse à dents': ['brosse a dents', 'brosse à dents'],
            'savon': ['savon'],
            'papier toilette': ['papier toilette'],
            'poubelle': ['poubelle'],
            'aspirateur': ['aspirateur'],
            'panier': ['panier'],
            'oreiller': ['oreiller'],
            'drap': ['drap'],
            'couverture': ['couverture'],
            'rideau': ['rideau'],
            'plante': ['plante'],
            'fleur': ['fleur'],
            'bougie': ['bougie'],
            'sonnette': ['sonnette'],
            'radio': ['radio'],
            't-shirt': ['t-shirt', 'tshirt', 'tee-shirt'],
            'pantalon': ['pantalon'],
            'robe': ['robe'],
            'manteau': ['manteau'],
            'chaussure': ['chaussure'],
            'chaussette': ['chaussette'],
            'écharpe': ['echarpe', 'écharpe'],
            'gant': ['gant'],
            'chapeau': ['chapeau'],
            'casquette': ['casquette'],
            'bague': ['bague', 'anneau'],
            'parapluie': ['parapluie'],
            'petit déjeuner': ['petit dejeuner', 'petit déjeuner'],
            'déjeuner': ['dejeuner', 'déjeuner'],
            'dîner': ['diner', 'dîner'],
            'peluche': ['peluche'],
            'jeu vidéo': ['jeu video', 'jeu vidéo'],
            'bibliothèque': ['bibliotheque', 'bibliothèque'],
            'tapis': ['tapis', 'moquette'],
            'table': ['table'],
            'salle à manger': ['salle a manger', 'salle à manger'],
            'salon': ['salon', 'sejour', 'séjour'],
            'chambre': ['chambre'],
            'cuisine': ['cuisine'],
            'salle de bain': ['salle de bain'],
            'garage': ['garage'],
            'grenier': ['grenier'],
            'sous-sol': ['sous-sol', 'sous sol', 'cave'],
            'arbre': ['arbre'],
            'tournesol': ['tournesol'],
            'chien': ['chien', 'toutou'],
            'chat': ['chat', 'minou'],
            'oiseau': ['oiseau'],
            'lune': ['lune'],
            'soleil': ['soleil'],
            'étoile': ['etoile', 'étoile'],
            'arc-en-ciel': ['arc-en-ciel', 'arc en ciel'],
            'nuage': ['nuage'],
            'pluie': ['pluie'],
            'four à pizza': ['four a pizza', 'four à pizza'],
        }
    };

    // Build synonym map: for each language, map the canonical word to its synonyms
    for (const lang of ['es', 'en', 'fr']) {
        // Start with manual entries
        if (manualSyns[lang]) {
            for (const [word, variants] of Object.entries(manualSyns[lang])) {
                syns[lang][word.toLowerCase()] = variants.map(v => v.toLowerCase());
            }
        }
        // Ensure every word from categoryData has at least itself as synonym
        for (const cat of Object.values(categoryData)) {
            for (const item of cat.items) {
                const w = item[lang]?.toLowerCase();
                if (w && !syns[lang][w]) {
                    syns[lang][w] = [w];
                }
            }
        }
    }
    return syns;
}

const wordSynonyms = buildSynonyms();
